# Generated by Django 3.0.2 on 2020-07-01 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=100)),
                ('author_name', models.CharField(default='', max_length=100)),
                ('original_price', models.IntegerField(default=0)),
                ('demand_price', models.IntegerField(default=0)),
                ('book_img', models.ImageField(default='None', upload_to='Book_img')),
                ('stream', models.CharField(default='', max_length=100)),
                ('book_yr', models.IntegerField(default=0)),
                ('branch', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 's_books',
            },
        ),
    ]
