# Generated by Django 3.0.8 on 2020-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prof_img',
        ),
        migrations.AddField(
            model_name='user',
            name='mob_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
